CREATE SEQUENCE cena_paliwo_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER cena_paliwo_AI 
BEFORE INSERT ON cena_paliwo
FOR EACH ROW

BEGIN
 SELECT cena_paliwo_seq.NEXTVAL
 INTO   :new.id_cena_paliwo
 FROM   dual;
END;
/

CREATE SEQUENCE dodatek_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER dodatek_AI 
BEFORE INSERT ON dodatek
FOR EACH ROW

BEGIN
 SELECT dodatek_seq.NEXTVAL
 INTO   :new.id_dodatek
 FROM   dual;
END;
/
CREATE SEQUENCE dost_paliwa_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER dost_paliwa_AI 
BEFORE INSERT ON dost_paliwa
FOR EACH ROW

BEGIN
 SELECT dost_paliwa_seq.NEXTVAL
 INTO   :new.id_dost_paliwa
 FROM   dual;
END;
/
CREATE SEQUENCE dys_stat_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER dys_stat_AI 
BEFORE INSERT ON dys_stat
FOR EACH ROW

BEGIN
 SELECT dys_stat_seq.NEXTVAL
 INTO   :new.id_dys_status
 FROM   dual;
END;
/

CREATE SEQUENCE dystrybutor_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER dystrybutor_AI 
BEFORE INSERT ON dystrybutor
FOR EACH ROW

BEGIN
 SELECT dystrybutor_seq.NEXTVAL
 INTO   :new.id_dystrybutor
 FROM   dual;
END;
/
CREATE SEQUENCE faktura_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER faktura_AI 
BEFORE INSERT ON faktura
FOR EACH ROW

BEGIN
 SELECT faktura_seq.NEXTVAL
 INTO   :new.id_faktura
 FROM   dual;
END;
/
CREATE SEQUENCE firma_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER firma_AI 
BEFORE INSERT ON firma
FOR EACH ROW

BEGIN
 SELECT firma_seq.NEXTVAL
 INTO   :new.id_firma
 FROM   dual;
END;
/
CREATE SEQUENCE klient_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER klient_AI 
BEFORE INSERT ON klient
FOR EACH ROW

BEGIN
 SELECT klient_seq.NEXTVAL
 INTO   :new.id_klient
 FROM   dual;
END;
/
CREATE SEQUENCE koszyk_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER koszyk_AI 
BEFORE INSERT ON koszyk
FOR EACH ROW

BEGIN
 SELECT koszyk_seq.NEXTVAL
 INTO   :new.id_koszyk
 FROM   dual;
END;
/
CREATE SEQUENCE paragon_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER paragon_AI 
BEFORE INSERT ON paragon
FOR EACH ROW

BEGIN
 SELECT paragon_seq.NEXTVAL
 INTO   :new.id_paragon
 FROM   dual;
END;
/
CREATE SEQUENCE pensja_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER pensja_AI 
BEFORE INSERT ON pensja
FOR EACH ROW

BEGIN
 SELECT pensja_seq.NEXTVAL
 INTO   :new.id_pensja
 FROM   dual;
END;
/
CREATE SEQUENCE pracownik_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER pracownik_AI 
BEFORE INSERT ON pracownik
FOR EACH ROW

BEGIN
 SELECT pracownik_seq.NEXTVAL
 INTO   :new.id_pracownik
 FROM   dual;
END;
/
CREATE SEQUENCE rodz_pal_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER rodz_pal_AI 
BEFORE INSERT ON rodz_pal
FOR EACH ROW

BEGIN
 SELECT rodz_pal_seq.NEXTVAL
 INTO   :new.id_rodz_pal
 FROM   dual;
END;
/
CREATE SEQUENCE stan_zatr_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER stan_zatr_AI 
BEFORE INSERT ON stan_zatr
FOR EACH ROW

BEGIN
 SELECT stan_zatr_seq.NEXTVAL
 INTO   :new.id_stan_zatr
 FROM   dual;
END;
/
CREATE SEQUENCE stanowisko_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER stanowisko_AI 
BEFORE INSERT ON stanowisko
FOR EACH ROW

BEGIN
 SELECT stanowisko_seq.NEXTVAL
 INTO   :new.id_stanowisko
 FROM   dual;
END;
/
CREATE SEQUENCE status_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER status_AI 
BEFORE INSERT ON status
FOR EACH ROW

BEGIN
 SELECT status_seq.NEXTVAL
 INTO   :new.id_status
 FROM   dual;
END;
/
CREATE SEQUENCE towar_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER towar_AI 
BEFORE INSERT ON towar
FOR EACH ROW

BEGIN
 SELECT towar_seq.NEXTVAL
 INTO   :new.id_towar
 FROM   dual;
END;
/
CREATE SEQUENCE ubezp_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER ubezp_AI 
BEFORE INSERT ON ubezp
FOR EACH ROW

BEGIN
 SELECT ubezp_seq.NEXTVAL
 INTO   :new.id_ubezp
 FROM   dual;
END;
/
CREATE SEQUENCE zam_stacji_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER zam_stacji_AI 
BEFORE INSERT ON zam_stacji
FOR EACH ROW

BEGIN
 SELECT zam_stacji_seq.NEXTVAL
 INTO   :new.id_zam_stacji
 FROM   dual;
END;
/
CREATE SEQUENCE zamowienie_seq START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999;

CREATE OR REPLACE TRIGGER zamowienie_AI 
BEFORE INSERT ON zamowienie
FOR EACH ROW

BEGIN
 SELECT zamowienie_seq.NEXTVAL
 INTO   :new.id_zamowienie
 FROM   dual;
END;
/
