-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2121
--   at:        2018-05-21 14:23:33 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

--DROP TABLE stanowisko CASCADE CONSTRAINTS;
    
    
CREATE TABLE cena_paliwo (
    id_cena_paliwo   NUMBER NOT NULL,
    cena             NUMBER NOT NULL
);
ALTER TABLE cena_paliwo ADD CONSTRAINT cena_paliwo_pk PRIMARY KEY ( id_cena_paliwo );
    

CREATE TABLE dodatek (
    id_dodatek         NUMBER(11) NOT NULL,
    dodatek            NUMBER(8)
);
ALTER TABLE dodatek ADD CONSTRAINT dodatek_pk PRIMARY KEY ( id_dodatek );



CREATE TABLE dost_paliwa (
    id_dost_paliwa   NUMBER(8) NOT NULL,
    nazwa_dostawcy   VARCHAR2(50) NOT NULL
);
ALTER TABLE dost_paliwa ADD CONSTRAINT dost_paliwa_pk PRIMARY KEY ( id_dost_paliwa );




CREATE TABLE dys_stat (
    id_dys_status     NUMBER(9) NOT NULL,
    ile_litrow_zost   NUMBER NOT NULL
);
ALTER TABLE dys_stat ADD CONSTRAINT dys_stat_pk PRIMARY KEY ( id_dys_status );


CREATE TABLE dystrybutor (
    id_dystrybutor               NUMBER NOT NULL,
    numer_dystrybutora           NUMBER NOT NULL,
    cena_paliwo_id_cena_paliwo   NUMBER NOT NULL,
    rodz_pal_id_rodz_pal         NUMBER NOT NULL,
    dys_stat_id_dys_status       NUMBER(9) NOT NULL
);
ALTER TABLE dystrybutor ADD CONSTRAINT dystrybutor_pk PRIMARY KEY ( id_dystrybutor );




--DROP TABLE faktura CASCADE CONSTRAINTS;
CREATE TABLE faktura (
    id_faktura                 NUMBER NOT NULL,
    nip                        VARCHAR2(15),
    nazwa_firmy                VARCHAR2(40),
    data_wystawienia           VARCHAR2(20)
);
ALTER TABLE faktura ADD CONSTRAINT faktura_pk PRIMARY KEY ( id_faktura );




CREATE TABLE firma (
    id_firma       NUMBER NOT NULL,
    miejscowosc    VARCHAR2(30) NOT NULL,
    kod_pocztowy   VARCHAR2(6) NOT NULL,
    ulica          VARCHAR2(30) NOT NULL
);
ALTER TABLE firma ADD CONSTRAINT firma_pk PRIMARY KEY ( id_firma );




CREATE TABLE klient (
    id_klient          NUMBER(8) NOT NULL,
    imie               VARCHAR2(30) NOT NULL,
    nazwisko           VARCHAR2(30) NOT NULL,
    miejscowosc        VARCHAR2(40) NOT NULL,
    ulica              VARCHAR2(30) NOT NULL,
    numer_mieszkania   VARCHAR2(10),
    numer_domu         VARCHAR2(20) NOT NULL
);
ALTER TABLE klient ADD CONSTRAINT klient_pk PRIMARY KEY ( id_klient );




CREATE TABLE koszyk (
    id_koszyk              NUMBER NOT NULL,
    suma_zamowienia        NUMBER NOT NULL,
    klient_id_klient       NUMBER(8) NOT NULL,
    firma_id_firma         NUMBER NOT NULL,
    faktura_id_faktura     NUMBER NOT NULL,
    paragon_id_paragon     NUMBER(8) NOT NULL,
    status_id_status       NUMBER NOT NULL,
    id_zam_stacji   NUMBER 
);

ALTER TABLE koszyk ADD CONSTRAINT koszyk_pk PRIMARY KEY ( id_koszyk );




CREATE TABLE paragon (
    id_paragon         NUMBER(8) NOT NULL,
    data_wystawienia   VARCHAR2(20) NOT NULL
);
ALTER TABLE paragon ADD CONSTRAINT paragon_pk PRIMARY KEY ( id_paragon );




CREATE TABLE pensja (
    id_pensja          NUMBER(11) NOT NULL,
    pensja             NUMBER(10)
);
ALTER TABLE pensja ADD CONSTRAINT pensja_pk PRIMARY KEY ( id_pensja );




CREATE TABLE pracownik (
    id_pracownik               NUMBER(11) NOT NULL,
    imie                       VARCHAR2(20) NOT NULL,
    nazwisko                   VARCHAR2(30) NOT NULL,
    pesel                      NUMBER(11) NOT NULL,
    miejscowosc                VARCHAR2(20) NOT NULL,
    kod_pocztowy               VARCHAR2(30) NOT NULL,
    ulica                      VARCHAR2(30) NOT NULL,
    numer_domu                 VARCHAR2(10) NOT NULL,
    numer_mieszkania           VARCHAR2(6),
    pensja_id_pensja           NUMBER(11) NOT NULL,
    dodatek_id_dodatek         NUMBER(11) NOT NULL,
    stanowisko_id_stanowisko   NUMBER(11) NOT NULL,
    ubezp_id_ubezp             NUMBER(11) NOT NULL,
    stan_zatr_id_stan_zatr     NUMBER(11) NOT NULL
);
ALTER TABLE pracownik ADD CONSTRAINT pracownik_pk PRIMARY KEY ( id_pracownik );




CREATE TABLE rodz_pal (
    id_rodz_pal   NUMBER NOT NULL,
    rodzaje       VARCHAR2(30) NOT NULL
);
ALTER TABLE rodz_pal ADD CONSTRAINT rodz_pal_pk PRIMARY KEY ( id_rodz_pal );




CREATE TABLE stan_zatr (
    czy_zatrudniony          VARCHAR2(10) NOT NULL,
    id_stan_zatr     NUMBER NOT NULL
);
ALTER TABLE stan_zatr ADD CONSTRAINT stan_zatr_pk PRIMARY KEY ( id_stan_zatr );




CREATE TABLE stanowisko (
    id_stanowisko       NUMBER(11) NOT NULL,
    nazwa_stanowiska    VARCHAR2(20) NOT NULL
);
ALTER TABLE stanowisko ADD CONSTRAINT stanowisko_pk PRIMARY KEY ( id_stanowisko );




CREATE TABLE status (
    id_status   NUMBER NOT NULL,
    status      VARCHAR2(40) NOT NULL
);
ALTER TABLE status ADD CONSTRAINT status_pk PRIMARY KEY ( id_status );





CREATE TABLE towar (
    id_towar              NUMBER NOT NULL,
    nazwa_rodzaj_paliwa   VARCHAR2(30) NOT NULL,
    ilosc_paliwa          NUMBER(11) NOT NULL
);
ALTER TABLE towar ADD CONSTRAINT towar_pk PRIMARY KEY ( id_towar );




CREATE TABLE ubezp (
    id_ubezp         NUMBER(8) NOT NULL,
    nazwa_ubezp      VARCHAR2(20) NOT NULL
);
ALTER TABLE ubezp ADD CONSTRAINT ubezp_pk PRIMARY KEY ( id_ubezp );




CREATE TABLE zam_stacji (
    id_zam_stacji                NUMBER NOT NULL,
    towar                        VARCHAR2(30) NOT NULL,
    ilosc                        NUMBER NOT NULL,
    towar_id_towar               NUMBER NOT NULL,
    dost_paliwa_id_dost_paliwa   NUMBER(8) NOT NULL,
    faktura_id_faktura           NUMBER NOT NULL,
    status_id_status             NUMBER NOT NULL
);

ALTER TABLE zam_stacji ADD CONSTRAINT zam_stacji_pk PRIMARY KEY ( id_zam_stacji );




CREATE TABLE zamowienie (
    id_zamowienie                NUMBER NOT NULL,
    ilosc                        INTEGER NOT NULL,
    koszyk_id_koszyk             NUMBER NOT NULL,
    pracownik_id_pracownik       NUMBER(11) NOT NULL,
    dystrybutor_id_dystrybutor   NUMBER NOT NULL
);
ALTER TABLE zamowienie ADD CONSTRAINT zamowienie_pk PRIMARY KEY ( id_zamowienie );




ALTER TABLE dystrybutor
    ADD CONSTRAINT dystrybutor_cena_paliwo_fk FOREIGN KEY ( cena_paliwo_id_cena_paliwo )
        REFERENCES cena_paliwo ( id_cena_paliwo );
ALTER TABLE dystrybutor
    ADD CONSTRAINT dystrybutor_dys_stat_fk FOREIGN KEY ( dys_stat_id_dys_status )
        REFERENCES dys_stat ( id_dys_status );
ALTER TABLE dystrybutor
    ADD CONSTRAINT dystrybutor_rodz_pal_fk FOREIGN KEY ( rodz_pal_id_rodz_pal )
        REFERENCES rodz_pal ( id_rodz_pal );
        
        

ALTER TABLE koszyk
    ADD CONSTRAINT koszyk_faktura_fk FOREIGN KEY ( faktura_id_faktura )
        REFERENCES faktura ( id_faktura );
ALTER TABLE koszyk
    ADD CONSTRAINT koszyk_firma_fk FOREIGN KEY ( firma_id_firma )
        REFERENCES firma ( id_firma );
ALTER TABLE koszyk
    ADD CONSTRAINT koszyk_klient_fk FOREIGN KEY ( klient_id_klient )
        REFERENCES klient ( id_klient );
ALTER TABLE koszyk
    ADD CONSTRAINT koszyk_paragon_fk FOREIGN KEY ( paragon_id_paragon )
        REFERENCES paragon ( id_paragon );
ALTER TABLE koszyk
    ADD CONSTRAINT koszyk_status_fk FOREIGN KEY ( status_id_status )
        REFERENCES status ( id_status );
ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_dodatek_fk FOREIGN KEY ( dodatek_id_dodatek )
        REFERENCES dodatek ( id_dodatek );
ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_pensja_fk FOREIGN KEY ( pensja_id_pensja )
        REFERENCES pensja ( id_pensja );
ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_stanowisko_fk FOREIGN KEY ( stanowisko_id_stanowisko )
        REFERENCES stanowisko ( id_stanowisko );
ALTER TABLE zam_stacji
    ADD CONSTRAINT zam_stacji_faktura_fk FOREIGN KEY ( faktura_id_faktura )
        REFERENCES faktura ( id_faktura );
ALTER TABLE zam_stacji
    ADD CONSTRAINT zam_stacji_status_fk FOREIGN KEY ( status_id_status )
        REFERENCES status ( id_status );
ALTER TABLE zam_stacji
    ADD CONSTRAINT zam_stacji_towar_fk FOREIGN KEY ( towar_id_towar )
        REFERENCES towar ( id_towar );
ALTER TABLE zamowienie
    ADD CONSTRAINT zamowienie_dystrybutor_fk FOREIGN KEY ( dystrybutor_id_dystrybutor )
        REFERENCES dystrybutor ( id_dystrybutor );
ALTER TABLE zamowienie
    ADD CONSTRAINT zamowienie_koszyk_fk FOREIGN KEY ( koszyk_id_koszyk )
        REFERENCES koszyk ( id_koszyk );
ALTER TABLE zamowienie
    ADD CONSTRAINT zamowienie_pracownik_fk FOREIGN KEY ( pracownik_id_pracownik )
        REFERENCES pracownik ( id_pracownik );
-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            21
-- CREATE INDEX                             7
-- ALTER TABLE                             45
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0